//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnSpaceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtsyItemDb
    {
        public int Id { get; set; }
        public string Listing_Id { get; set; }
        public string Title { get; set; }
        public string Price { get; set; }
        public string Currency_Code { get; set; }
        public string Item_Length { get; set; }
        public string Item_Width { get; set; }
        public string Item_Height { get; set; }
        public string Item_Dimensions_Unit { get; set; }
        public string Url { get; set; }
        public string ImageThumbUrl { get; set; }
        public string ImageFullUrl { get; set; }
        public string Description { get; set; }
    }
}
