//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnSpaceWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSpace
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Listing { get; set; }
        public string QRCode { get; set; }
        public string Name { get; set; }
    }
}
